### ISSUE TITLE
support brcm4330 on linux

### ISSUE THREAD

**Issue by Dreem-Devices** [warpboard/linux-imx6#2]
Hi,

I am currently trying to build a linux distribution using buildroot for the warpboard. I am able to boot on the warpboard with my linux but the bluetooth and wifi does not work at all.

Current status is : 
- brcm4330 firmware is in the rootfs : 
  # ls /lib/firmware/brcm/
  
  bcm4329-fullmac-4.bin  brcmfmac-sdio.bin      brcmfmac4334-sdio.bin
  bcm43xx-0.fw           brcmfmac4329-sdio.bin  brcmfmac4335-sdio.bin
  bcm43xx_hdr-0.fw       brcmfmac4330-sdio.bin
- I enable the brcmfmac in staging driver. I use modprobe to load it
- No hci0, no wlan0 ..

I try some command found on the wandboard community ( another board which seems to use the brcm4330 chipset from Broadcom) but without any success : 
# ./brcm_patchram_plus -d --patchram bcm4330.hcd --baudrate 3000000 --use_baudra

te_for_download /dev/ttymxc2  --enable_hci --no2bytes --enable_lpm
option patchram with arg bcm4330.hcd
option baudrate with arg 3000000
option use_baudrate_for_download
option enable_hci
option no2bytes
option enable_lpm
/dev/ttymxc2
writing
01 03 0c 00
read_event...
writing
01 03 0c 00
writing
01 03 0c 00
received -1094775952
select() returned error, errno=4
writing
01 18 fc 06 00 00 c0 c6 2d 00
read_event...

Could you help to to make it work or give me some track to follow ? 

Thanks,
Eva.

**Comment by diegorondini** [comment]
Hi. I think you are confusing WaRPboard (http://www.warpboard.org/) and Wandboard (http://www.wandboard.org/). I think you're using the latter, while this repository is for the former.

**Comment by Sam-Dreem** [comment]
Hi Diego,

There is no confusion. We obtained two BETA WaRP boards by Freescale and we try to develop a Linux BSP for it. The main difficulties we have met deal with radio module (BT & WIFI) especially how to load the firmware.

We try to reproduce in Linux the behaviour observed in Android image that has been provided. However, the git repos do not seem up-to-date, branches are several commits ahead, several behind. For now, we use the Murata branch of the kernel that seems to be the closest one.

Our current boot log is similar to the Android one, all peripherals seem power on. But we miss the layer between kernel and userspace, like firmware loading for radio. We built the platform_hardware_broadcom_libbt but we do not undertand how to interact with it.
- Could you help us about BCM4330 configuration as you had to do it for the Android? Do we have to load bcm4330.hcd firmware? If yes, how? How to use libbt? Do you have any trick or advice to set it up?
- More generally, how to rebuild the full Android image (repo, branch, up-to-date) ? Are all the needed sources in these git repos? Are they up-to-date? Which branches do we have to use ? We tried to use the manifest provided but many links has failed. Seeing all sources should help us to reproduce the behaviour in Linux.

Thanks for your answers
